info:
  profile: dev


name: Saul
words: 'God bless me'

framework: '{cipher}6deeb9862d9c0b1c3cc18dac500c5f4f0a1ac693830bf2818b48175ec736b182'
  
config:
  info: "master branch, springcloud-config/config-dev.yml version=5"
